### ISSUE TITLE
follow the guide about openstack part, the cli can not work

### ISSUE THREAD

**Issue by HackToday** [emccode/rexray#178]
I tried the guide doc as https://github.com/emccode/rexray
and https://github.com/emccode/rexray/blob/master/.docs/user-guide/openstack.md

the config file as below
******************************
cat  /etc/rexray/config.yml 
openstack:
    authURL:              http://identity-ip:5000/v2.0
    userID:               0
    userName:             admin
    password:             password
    tenantID:             0
    tenantName:           admin
    domainID:             0
    domainName:           corp
    regionName:           RegionOne
    availabilityZoneName: nova
storageDrivers:
- openstack

**********************************

Then the cli would get following errors:

$ rexray volume get
Oops, an error occured!

  no storage drivers initialized

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/emccode/rexray
  - The on?.ne he?. be?.w

Get one or more volumes

Usage: 
  rexray volume get [flags]

It seems doc is not good for new beginners or some issue for the rexray

**Comment by clintonskitson** [comment]
Hello!

We are updating docs to include exact config files.


Here is a working example.  You can run this with `rexray volume -l debug` if you have issues to get more information.  
```
storageDrivers:
    - openstack
openstack:
    authUrl: https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/
    tenantName: 10677883784544-Project
    regionName: region-a.geo-1
    username: clintonskitson
    password: blah
```
