### ISSUE TITLE
Rexrey don't support HA to transfer the container with cinder volume to another normal slave node.

### ISSUE THREAD

**Issue by wangqunOne** [emccode/rexray#243]
we have setup the rexrey on one mesos cluster to test the rexrey if support HA to transfer the container with the cinder volume . I have three nodes. One Master Node, and two Nodes are slave nodes.
1. I create cinder volume  by the rexrey successfully on one slave node . And the cinder can also be attached to the container.
2.I stop the slave node that create the container with the cinder volume by the command "nova stop  instance_id" .
I find the container can transfer to the remaining slave node, but the status of the container is created not to be up. After minintes. I find so many same contain to be create. Their status all are created.  And the volume still is attached on the stop slave node.
From my test, it seems that the rexrey don't support HA to transfer the container with the cinder volume to the another slave node. Could any developer  confirmed that?

**Comment by wangqunOne** [comment]
@clintonskitson

**Comment by clintonskitson** [comment]
This functionality would likely require that you use the pre-emptive mount feature that we introduced in 0.3.0.  This feature is enabled with a similar config to the one below where we set the preempt flag to true.  If this is set, then RR will be able to attain control and mount a volume wherever it is needed irrespective of whether it is currently attached somewhere else.

```
rexray:
  storageDrivers:
  - openstack
  volume:
    mount:
      preempt: true
openstack:
  authUrl: http://host:35357/v2.0
  username: admin
  password: admin
  tenantName: demo
  regionName: RegionOne
  availabilityZone: nova
```
