### ISSUE TITLE
documented default config.yml does not work

### ISSUE THREAD

**Issue by codenrhoden** [emccode/rexray#250]
The docs currently list the following as the default config:

```yaml
---
rexray:
  logLevel: warn
  osDrivers:
  - linux
  storageDrivers:
  volumeDrivers:
  - docker
```

When I use that config at /etc/rexray/config.yml, I get an error like the following:

```console
# rexray version
ERROR: 2016/01/07 svType != tvType; key=storageDrivers, st=<nil>, tt=[]interface {}, sv=<nil>, tv=[libstorage]
ERROR: 2016/01/07 svType != tvType; key=storageDrivers, st=<nil>, tt=[]interface {}, sv=<nil>, tv=[libstorage]
ERROR: 2016/01/07 svType != tvType; key=storageDrivers, st=<nil>, tt=[]interface {}, sv=<nil>, tv=[libstorage]
Binary: /usr/bin/rexray
SemVer: 0.3.1
OsArch: Linux-x86_64
Branch: v0.3.1
Commit: bf4d6eec8c931b10d1ec187de052a23c09681ac6
Formed: Wed, 30 Dec 2015 21:12:44 UTC
```

Seeing **libstorage** in the output made me curious:

```console
# rexray env | grep DRIVER
REXRAY_VOLUMEDRIVERS=docker
REXRAY_OSDRIVERS=linux
REXRAY_STORAGEDRIVERS=libstorage
```

The docs make no mention of libstorage, not that it exists or that it is the default.

The docs make it look like you should enable storage drivers by listing them out like:

```yaml
---
rexray:
  storageDrivers:
  - openstack
  - scaleio
```

And then making config entries for each one, like:
```yaml
openStack:
  authUrl: https://authUrl:35357/v2.0/
  username: username
  password: password
  tenantName: tenantName
  regionName: regionName
scaleio:
  userid: xxx
  password: xxx
```

But our workshops use libstorage, and configure it differently:
```yaml
---
storageDrivers:
- libstorage
libstorage:
  host: "127.0.0.1:1870"
  drivers:
  - openstack
  - scaleio
  profiles:
    enabled: true
    client: false
    groups:
    - groupName=127.0.0.1
openStack:
  authUrl: https://authUrl:35357/v2.0/
  username: username
  password: password
  tenantName: tenantName
  regionName: regionName
scaleio:
  userid: xxx
  password: xxx
```

I think this is an area to be explained, cleaned up.  I'll see what I can do!  Reading the docs, I am confused about libstorage and how to use it, and if I am required to do so.
