### ISSUE TITLE
Received connection refused from CLI when libStorage host+service provided (0.4.0-rc3)

### ISSUE THREAD

**Issue by vladimirvivien** [emccode/rexray#461]
The following configuration causes the CLI to error out with a connection refused.  This is true for either `embedded` set to `true` or `false`.
```
rexray:
  modules:
    default-docker:
      libstorage:
        service: kubernetes
  libstorage:
    host: tcp://127.0.0.1:7980
    embedded: false
    server:
      endpoints:
        localhost:
          address: tcp://:7980
      services:
        kubernetes:
          libstorage:
            storage:
              driver: virtualbox
virtualbox:
  endpoint: http://10.0.2.2:18083
  tls: false
  volumePath: /Users/vladimir/VirtualBox Volumes
  controllerName: SATA Controller
```

### Version Info
```
REX-Ray
-------
Binary: /usr/bin/rexray
SemVer: 0.4.0-rc3+7
OsArch: Linux-x86_64
Branch: master
Commit: 7392b93b054bfd7afa5da6bfcce0ade036667f0a
Formed: Sat, 11 Jun 2016 03:34:15 UTC

libStorage
----------
SemVer: 0.1.1
OsArch: Linux-x86_64
Branch: master
Commit: dd2d78843bf7bd21a396c92036e4078b244b5de5
Formed: Sat, 11 Jun 2016 03:33:39 UTC

time="2016-06-14T15:21:52Z" level=panic msg="Get http://127.0.0.1:7980/services: dial tcp 127.0.0.1:7980: getsockopt: connection refused"
```
