### ISSUE TITLE
performance degradation with rexray 0.4.0 when compared to 0.3.3

### ISSUE THREAD

**Issue by cduchesne** [emccode/rexray#490]
Using REX-Ray  0.4.0, I have noticed that performance is much slower than with REX-Ray 0.3.3. In the case of listing volumes, performance slows down significantly as quantity of volumes on the storage system go up. I have only tested with ScaleIO, so I am not certain if this is the case with other drivers as of yet. Below are a couple of scenarios that I have tested to highlight the issue. Of the scenarios tested, I would highlight the listing volumes performance as the most worrisome, as I wouldn't be surprised for back-end storage systems to have significantly more volumes than I have tested; it is also one of the more frequently run functions.

#### Listing Volumes:
RR 0.3.3 w/ 10 volumes:
```
[root@rexray-0.3.3 ~]# time rexray volume ls > /dev/null

real	0m0.208s
user	0m0.091s
sys		0m0.052s
```

RR 0.4.0 w/ 10 volumes:
```
[root@rexray-0.4.0 ~]# time curl -so /dev/null http://127.0.0.1:7980/volumes

real	0m0.870s
user	0m0.008s
sys		0m0.007s
```

RR 0.3.3 w/ 100 volumes:
```
[root@rexray-0.3.3 ~]# time rexray volume ls > /dev/null

real	0m0.247s
user	0m0.133s
sys		0m0.054s
```

RR 0.4.0 w/ 100 volumes:
```
[root@rexray-0.4.0 ~]# time curl -so /dev/null http://127.0.0.1:7980/volumes

real	0m1.656s
user	0m0.008s
sys		0m0.009s

```

RR 0.3.3 w/ 250 volumes:
```
[root@rexray-0.3.3 ~]# time rexray volume ls > /dev/null

real	0m0.302s
user	0m0.212s
sys		0m0.057s
```

RR 0.4.0 w/ 250 volumes:
```
[root@rexray-0.4.0  ~]# time curl -so /dev/null http://127.0.0.1:7980/volumes

real	0m3.050s
user	0m0.008s
sys		0m0.009s
```

#### Attaching Volumes:
Performance was similar regardless of quantity of volumes (10/100/250)
RR 0.3.3:
```
[root@rexray-0.3.3 ~]# time rexray volume attach --volumeid 0ff3c49400000002

real	0m1.403s
user	0m0.135s
sys		0m0.174s
```

RR 0.4.0:
```
[root@rexray-0.4.0 ~]# time curl -H "libStorage-InstanceID: scaleio=ba90fc8b00000000" -X POST http://127.0.0.1:7980/volumes/scaleio/0ff3c49400000002?attach

real	0m2.242s
user	0m0.008s
sys		0m0.010s
```

#### Detaching Volumes:
Performance was similar regardless of quantity of volumes (10/100/250)

RR 0.3.3:
```
[root@rexray-0.3.3 ~]# time rexray volume detach --volumeid 0ff3c49400000002

real	0m0.266s
user	0m0.080s
sys		0m0.041s
```

RR 0.4.0:
```
[root@rexray-0.4.0 ~]# time curl -H "libStorage-InstanceID: scaleio=ba90fc8b00000000" -X POST http://127.0.0.1:7980/volumes/scaleio/0ff3c49400000002?detach

real	0m1.663s
user	0m0.009s
sys		0m0.009s
```

#### Inspecting Volumes
Performance was similar regardless of number of volumes (10/100/250)
REX-Ray 0.3.3:
```
[root@rexray-0.3.3 ~]# time rexray volume get --volumeid 0ff3c49200000000

real	0m0.214s
user	0m0.080s
sys		0m0.058s
```

RR 0.4.0:
```
[root@rexray-0.4.0 ~]# time curl -H "libStorage-InstanceID: scaleio=ba90fc8b00000000" -X GET http://127.0.0.1:7980/volumes/scaleio/0ff3c49200000000

real	0m1.052s
user	0m0.007s
sys		0m0.008s
```

#### Versions
RR 0.3.3 Version:
```
[root@rexray-0.3.3 ~]# rexray version
Binary: /usr/bin/rexray
SemVer: 0.3.3
OsArch: Linux-x86_64
Branch: v0.3.3
Commit: b30fb870b5b94cd8368824460ad020bfcf20be3a
Formed: Thu, 21 Apr 2016 12:41:36 PDT
```
RR 0.4.0 Version:
```
[root@rexray-0.4.0 ~]# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
SemVer: 0.4.0
OsArch: Linux-x86_64
Branch: v0.4.0
Commit: 2ee18a5be342ce038d65e9918f18fd22c0313fd3
Formed: Mon, 20 Jun 2016 20:52:17 PDT

libStorage
----------
SemVer: 0.1.3
OsArch: Linux-x86_64
Branch: v0.4.0
Commit: 182a626937677a081b89651598ee2eac839308e7
Formed: Mon, 20 Jun 2016 20:51:40 PDT
```

#### Configurations
RR 0.3.3 Config:
```
[root@rexray-0.3.3 ~]# cat /etc/rexray/config.yml
rexray:
  storageDrivers:
  - ScaleIO
  volume:
    mount:
      preempt: true
    unmount:
      ignoreusedcount: true
docker:
  fsType: xfs
scaleio:
  endpoint: https://scaleio-gateway/api
  insecure: true
  userName: admin
  password: ********
  systemName: scaleio
  protectionDomainName: default
  storagePoolName: default
```

RR 0.4.0 Config:
```
[root@rexray-0.4.0 ~]# cat /etc/rexray/config.yml
libstorage:
  service: scaleio
  server:
    endpoints:
      localhost:
        address: tcp://:7980
scaleio:
  endpoint: https://scaleio-gateway/api
  apiVersion: "2.0"
  insecure: true
  userName: admin
  password: ********
  systemName: scaleio
  protectionDomainName: default
  storagePoolName: default
```
