### ISSUE TITLE
RexRay URL Config For XtremIO 

### ISSUE THREAD

**Issue by carone1** [emccode/rexray#567]
Following this guide to configure RexRay on CentOS. https://rexray.readthedocs.io/en/v0.3.3/user-guide/storage-providers/#configuration_7

I installed the required RPMs listed in the prerequisite steps.  I also created an initiatior group on the XtremIO node.  

My rexray config.yml looks similar to what is suggested by the guide.  If I try to reach https://<xms_ip>/xtremio with a browser it fails.  If I try to start RexRay, I see a 404 error in the logs.  Is the documentation out of date as /xtremio doesn't seem to be valid url?  Anyway looking for a suggestion on proper endpoint url to use for XtremIO.

```
rexray:
  logLevel: debug
  storageDrivers:
  - xtremio
xtremio:
  endpoint: https://<xms_ip>/xtremio
  insecure: true
  username: admin
  password: password
  multipath: true
 ```
